name: astropy_rc_basic

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# These only prove that basic test suite in Linux works.
# It is up to the individual packages to do detailed testing with astropy RC.
jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@d9b81a07e789d1b1921ab5fe33de2ddcbbd02c3f  # v2.3.0
    with:
      submodules: false
      envs: |
        - linux: py311-asdf_astropy
        - linux: py311-asdf_astropy-dev
        - linux: py311-astropy_healpix
        - linux: py311-astropy_healpix-dev
        - linux: py311-ccdproc
        - linux: py311-ccdproc-dev
        - linux: py311-photutils
        - linux: py311-photutils-dev
        - linux: py311-regions
        - linux: py311-regions-dev
        - linux: py311-reproject
        - linux: py311-reproject-dev
        - linux: py311-specreduce
        - linux: py311-specreduce-dev
        - linux: py311-specutils
        - linux: py311-specutils-dev
        - linux: py311-sunpy
        - linux: py311-sunpy-dev
